CREATE TABLE ticket
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description TEXT,
    status      VARCHAR(255),
    priority    VARCHAR(255),
    employee_id BIGINT,
    asset_id    BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ticket PRIMARY KEY (id)
);

CREATE TABLE ticket_comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment    TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    ticket_id  BIGINT,
    CONSTRAINT pk_ticket_comment PRIMARY KEY (id)
);

CREATE TABLE ticket_status_history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    old_status VARCHAR(50),
    new_status VARCHAR(50),
    changed_at TIMESTAMP WITHOUT TIME ZONE,
    ticket_id  BIGINT,
    CONSTRAINT pk_ticket_status_history PRIMARY KEY (id)
);

ALTER TABLE ticket_comment
    ADD CONSTRAINT FK_TICKET_COMMENT_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES ticket (id);

ALTER TABLE ticket_status_history
    ADD CONSTRAINT FK_TICKET_STATUS_HISTORY_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES ticket (id);