quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url= jdbc:postgresql://localhost:5432/helpdesk
quarkus.hibernate-orm.database.default-schema=app_employee

quarkus.http.port=8085
quarkus.http.host=0.0.0.0

#cors
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

consul.host=127.0.0.1
consul.port=8500

quarkus.stork.tickets-api.service-discovery.type=consul
quarkus.stork.tickets-api.service-discovery.consul-host=${consul.host}
quarkus.stork.tickets-api.service-discovery.consul-port=${consul.port}
quarkus.stork.tickets-api.service-discovery.application=app-ticket
quarkus.stork.tickets-api.service-discovery.refresh-period=5s

#FLAYWAY
quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-at-start=false
quarkus.flyway.schemas=app_employee

#Swagger
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.allow-forwarded=true
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.urls.default=/app-employee/q/openapi
mp.openapi.servers=/app-employee
